CREATE DATABASE IF NOT EXISTS user_db;
USE user_db;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(80) NOT NULL,
  lastname  VARCHAR(80) NOT NULL,
  email     VARCHAR(190) NOT NULL UNIQUE,
  contactno VARCHAR(30)  NOT NULL,
  idno      VARCHAR(80)  NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
